from igfw.config.config import Configuration
from igfw.utils.ingestion_type import IngestionType
from igfw.ingestor.s3_ingestor import S3Ingestor
from igfw.ingestor.oracle_ingestor import OracleIngestor
from igfw.ingestor.mysql_ingestor import MySQLIngestor
from igfw.ingestor.postgre_ingestor import PostgreIngestor
from igfw.ingestor.sybase_ingestor import SybaseIngestor
from igfw.utils.ingestion_type import IngestionType
from igfw.utils.ingestion_factory import IngestionFactory